### ISSUE TITLE
In rule pre_umi_dedup: Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.nio.file.FileSystemException: 

### ISSUE THREAD

**Issue by byee4** [YeoLab/Mudskipper#4]
```
(snakemake738) [bay001@tscc-1-4 error_files]$ cat ./dedup.K562_rep6.RBFOX2
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Fri Mar 15 11:52:48 2024]
rule pre_umi_dedup:
  input: K562_rep6/bams/RBFOX2.Aligned.sortedByCoord.out.bam, K562_rep6/bams/RBFOX2.Aligned.sortedByCoord.out.bam.bai
  output: K562_rep6/bams/RBFOX2.rmDup.Aligned.sortedByCoord.out.bam
  jobid: 0
  benchmark: benchmarks/align/dedup.K562_rep6.RBFOX2.txt
  wildcards: libname=K562_rep6, sample_label=RBFOX2
  resources: mem_mb=3236, disk_mb=3236, tmpdir=/var/tmp


    java -server -Xms8G -Xmx8G -Xss20M -jar /UMICollapse/umicollapse.jar bam -i K562_rep6/bams/RBFOX2.Aligned.sortedByCoord.out.bam -o K562_rep6/bams/RBFOX2.rmDup.Aligned.sortedByCoord.out.bam --umi-sep : --two-pass --paired
     
Activating singularity image /tscc/nfs/home/hsher/scratch/singularity/3ed305f38a221faaa4d685ecac572559.simg
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
  3443253
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.nio.file.FileSystemException: /tmp/sortingcollection.14074251648559036317.tmp: No space left on device
    at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:268)
    at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:183)


```

**Comment by byee4** [comment]
This can be fixed by setting the tmpdir to somewhere else eg.

`export _JAVA_OPTIONS="-Djava.io.tmpdir=/tscc/lustre/ddn/scratch/bay001/"`
